Web.CMS/Controllers/CommentController.cs
using Azure.Core;
using Caching.Elasticsearch;
using Entities.ViewModels;
using Entities.ViewModels.Comment;
using HuloToys_Service.ElasticSearch.NewEs;
using Microsoft.AspNetCore.Mvc;
using Repositories.IRepositories;
using Repositories.Repositories;

namespace WEB.CMS.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentRepository _IcommentRepository;
        private readonly ClientESService _ClientESService;
        public CommentController(ICommentRepository icommentRepository,IConfiguration configuration)
        {
            _IcommentRepository = icommentRepository;
            _ClientESService = new ClientESService(configuration["DataBaseConfig:Elastic:Host"], configuration);

        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ListComment(CommentParamRequest request)
        {
            var lst = await _IcommentRepository.GetAllComment(request);
            return View(lst);
        }

        public async Task<GenericViewModel<CommentViewModel>> GetAllComment(CommentParamRequest request) 
        {
            return await _IcommentRepository.GetAllComment(request);
        }

        public async Task<IActionResult> Client(string phoneOrName) 
        {
            try
            {
                if (!string.IsNullOrEmpty(phoneOrName))
                    return Ok(new
                    {
                        is_success = true,
                        data = _ClientESService.GetClientByNameOrPhone(phoneOrName)
                    });
            }
            catch
            {

            }
            return Ok(new
            {
                is_success = false
            });
        }
    }
}

Web.CMS/ViewComponents/PagingV2ViewComponent.cs
using Entities.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WEB.CMS.ViewComponents
{
    public class PagingV2ViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Paging pageModel)
        {
            return View(pageModel);
        }
    }
}

Web.CMS/Views/Comment/Index.cshtml
@{
    ViewData["Title"] = "Quản lý Comments";
}
<style>
    .centered option{
        text-align: center;
    }

    .selection span
    {
        height: 35px !important;
    }

     .ClientInput_Arrow{
        display: none !important;
    }
</style>
<div class="bg-serach-main" style="width:100%,margin:0px">
    <div class="flex justify-between">
        <select class="select2 select2-hidden-accessible" onchange="_comment.OnChangeClient()" name="" id="clientInput" style="width: 88%;" tabindex="-1" aria-hidden="true">
        </select>
        <select class="select2 centered" name="" id="DateInput" onchange="_comment.OnChanggeDate()" style="width: 10%;" tabindex="-1" aria-hidden="true">
            <option class="" value="all" data-select2-id="select2-data-3-o5x9">
                <strong>Tất cả</strong>
            </option>
            <option class="mt-2" value="today">Hôm nay</option>
            <option class="mt-2" value="yesterday">Hôm qua</option>
            <option class="mt-2" value="thisWeek">Tuần này</option>
            <option class="mt-2" value="lastWeek">Tuần trước</option>
            <option class="mt-2" value="thisMonth">Tháng này</option>
            <option class="mt-2" value="lastMonth">Tháng trước</option>
            <option class="mt-2" value="thisQuarter">Quý này</option>
            <option class="mt-2" value="lastQuarter">Quý Trước</option>
        </select>
    </div>
    <div id="Comment-content">

    </div>
</div>
@section scripts {
    <script type="text/javascript" src="~/modules/comment.js" asp-append-version="true"></script>
}

Web.CMS/Views/Comment/ListComment.cshtml
@using Entities.ViewModels
@using Entities.ViewModels.Comment
@model GenericViewModel<CommentViewModel>
@{
    Layout = null;
}
<style>
    .OptionRow {
        vertical-align: middle !important;
    }

    .thead-fields {
        text-align: center;
    }

    .trow-fields {
        text-align: center;
    }

    table, th, td {
        border: 1px solid #CCCCCC;
    }
</style>
<table id="table-comment" class="table table-nowrap mt-3">
    <thead id="table-head">
        <tr class="bg-main2" style="background-color:#F3F5F8">
            <th class="thead-fields">STT</th>
            <th class="thead-fields">KHÁCH HÀNG</th>
            <th class="thead-fields">NỘI DUNG CÂU HỎI - PHẢN HỒI </th>
            <th class="thead-fields">NGÀY TẠO</th>
        </tr>
    </thead>
    <tbody id="table-comment-body">
        @if (Model.ListData != null && Model.ListData.Count > 0)
        {
            int STT = 0;
            if (Model.CurrentPage == 1)
            {
                STT = 1;
            }
            else
            {
                STT = ((Model.CurrentPage-1)*Model.PageSize) + 1;
            }
            foreach (var i in Model.ListData)
            {
                <tr>
                    <td class="OptionRow trow-fields">@STT</td>
                    <td class="OptionRow">
                        <div style="display: flex; flex-direction: column;">
                            <h5>@i.ClientName</h5>
                            <h7>@i.Phone</h7>
                            <h7>@i.Email</h7>
                        </div>
                    </td>
                    <td class="OptionRow" style="max-width:500px;word-wrap: break-word">
                        <div class="">@i.Content</div>
                    </td>
                    <td class="OptionRow">
                        <div class="trow-fields">@i.CreatedDate</div>
                    </td>

                </tr>
                STT += 1;
            }
        }
        else
        {
            <script>
                $('#table-head').html(``);
                $('#table-comment-body').html(``);
                $('#table-head').append(`
                                <div class="search-null center mb40">
                                    <div class="mb24">
                                        <img src="/images/graphics/icon-search.png" alt="">
                                    </div>
                                    <h2 class="title txt_24">Không tìm thấy kết quả</h2>
                                    <div class="gray">Chúng tôi không tìm thấy thông tin mà bạn cần, vui lòng thử lại</div>
                                </div>
                                `);
            </script>
        }
    </tbody>
</table>
@await Component.InvokeAsync("PagingV2", new
    {
        pageModel = new Paging()
    {
        TotalRecord = Model.TotalRecord,
        TotalPage = Model.TotalPage,
        CurrentPage = Model.CurrentPage,
        PageSize = Model.PageSize,
        RecordName = "Góp ý",
        PageAction = "_comment.OnPanging({0})"
    }
    })