Web.CMS/Controllers/Funding/ReceiptController.cs
using Entities.Models;
using Entities.ViewModels.Attachment;
using Entities.ViewModels.Funding;
using Entities.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Repositories.IRepositories;
using Repositories.Repositories;
using System.Security.Claims;
using Utilities;
using Utilities.Contants;
using WEB.Adavigo.CMS.Service;
using WEB.CMS.Customize;
using WEB.CMS.Models;
using Newtonsoft.Json;

namespace WEB.CMS.Controllers.Funding
{
    [CustomAuthorize]
    public class ReceiptController : Controller
    {
        private readonly IAllCodeRepository _allCodeRepository;
        private readonly IWebHostEnvironment _WebHostEnvironment;
        private readonly IClientRepository _clientRepository;

        private readonly IContractPayRepository _contractPayRepository;
        private IIdentifierServiceRepository identifierServiceRepository;
        private readonly IUserRepository _userRepository;
        private ManagementUser _ManagementUser;
        private readonly IOrderRepository _orderRepository;
        private readonly IDepositHistoryRepository _depositHistoryRepository;
        private readonly WEB.CMS.Models.AppSettings config;
        private readonly IConfiguration _configuration;
        private readonly IPaymentRequestRepository _paymentRequestRepository;

        public ReceiptController(IContractPayRepository contractPayRepository, IAllCodeRepository allCodeRepository, IWebHostEnvironment hostEnvironment,
          IClientRepository clientRepository, IDepositHistoryRepository depositHistoryRepository, IOrderRepository orderRepository, ManagementUser ManagementUser,
           IUserRepository userRepository, IIdentifierServiceRepository _identifierServiceRepository, IPaymentRequestRepository paymentRequestRepository,
           IConfiguration configuration)
        {

            _WebHostEnvironment = hostEnvironment;
            _clientRepository = clientRepository;
            _allCodeRepository = allCodeRepository;
            _contractPayRepository = contractPayRepository;
         
            _orderRepository = orderRepository;
            _ManagementUser = ManagementUser;
            _userRepository = userRepository;
            identifierServiceRepository = _identifierServiceRepository;
            _depositHistoryRepository = depositHistoryRepository;
            _paymentRequestRepository = paymentRequestRepository;

            _configuration = configuration;
            config = ReadFile.LoadConfig();
        }
        public IActionResult Index()
        {
            ViewBag.allCode_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.PAY_TYPE);
            ViewBag.allCode_CONTRACT_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.CONTRACT_PAY_TYPE);
            return View();
        }
        [HttpPost]
        public IActionResult Search(ContractPaySearchModel searchModel, int currentPage = 1, int pageSize = 20)
        {
            var model = new GenericViewModel<ContractPayViewModel>();
            try
            {
                if (searchModel.CreateByIds == null) searchModel.CreateByIds = new List<int>();
                if (!string.IsNullOrEmpty(searchModel.BillNo))
                    searchModel.BillNo = searchModel.BillNo.Trim();
                if (!string.IsNullOrEmpty(searchModel.Content))
                    searchModel.Content = searchModel.Content.Trim();
                var listContractPays = _contractPayRepository.GetListContractPay(searchModel, out long total, currentPage, pageSize);
                model.CurrentPage = currentPage;
                model.ListData = listContractPays;
                model.PageSize = pageSize;
                model.TotalRecord = total;
                model.TotalPage = (int)Math.Ceiling((double)total / pageSize);
            }
            catch (Exception ex)
            {
                LogHelper.InsertLogTelegram("Search - ReceiptController: " + ex);
            }
            return PartialView(model);
        }

        public IActionResult AddNew()
        {
            ViewBag.allCode_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.PAY_TYPE);
            ViewBag.allCode_CONTRACT_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.CONTRACT_PAY_TYPE);
            ViewBag.listBankingAccount = _allCodeRepository.GetBankingAccounts().Where(n => n.SupplierId ==
            (long)config.SUPPLIERID_ADAVIGO).ToList();
            return PartialView();
        }

        public IActionResult AddNewType()
        {
            ViewBag.allCode_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.PAY_TYPE);
            ViewBag.allCode_CONTRACT_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.CONTRACT_PAY_TYPE);
            ViewBag.listBankingAccount = _allCodeRepository.GetBankingAccounts().Where(n => n.SupplierId ==
            (long)config.SUPPLIERID_ADAVIGO).ToList();
            return PartialView();
        }

        public IActionResult Edit(int payId)
        {
            ViewBag.allCode_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.PAY_TYPE);
            ViewBag.allCode_CONTRACT_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.CONTRACT_PAY_TYPE);
            ViewBag.listBankingAccount = _allCodeRepository.GetBankingAccounts().Where(n => n.SupplierId ==
            (long)config.SUPPLIERID_ADAVIGO).ToList();
            var contractPay = _contractPayRepository.GetByContractPayId(payId);
            return PartialView(contractPay);
        }

        public IActionResult EditAdmin(int payId)
        {
            ViewBag.allCode_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.PAY_TYPE);
            ViewBag.allCode_CONTRACT_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.CONTRACT_PAY_TYPE);
            ViewBag.listBankingAccount = _allCodeRepository.GetBankingAccounts().Where(n => n.SupplierId ==
            (long)config.SUPPLIERID_ADAVIGO).ToList();
            var contractPay = _contractPayRepository.GetByContractPayId(payId);
            return PartialView(contractPay);
        }

        public IActionResult EditNewType(int payId)
        {
            ViewBag.allCode_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.PAY_TYPE);
            ViewBag.allCode_CONTRACT_PAY_TYPE = _allCodeRepository.GetListByType(AllCodeType.CONTRACT_PAY_TYPE);
            ViewBag.listBankingAccount = _allCodeRepository.GetBankingAccounts().Where(n => n.SupplierId ==
            (long)config.SUPPLIERID_ADAVIGO).ToList();
            var contractPay = _contractPayRepository.GetByPayId(payId);
            return PartialView(contractPay);
        }

        private int Validate(ContractPayViewModel model, out string message)
        {
            var result = 1;
            message = string.Empty;
            if (model.Type == 0)
            {
                message = "Vui lòng chọn loại nghiệp vụ";
                return -1;
            }
            if (model.PayType == 0)
            {
                message = "Vui lòng chọn hình thức";
                return -1;
            }
            if (model.ClientId == 0)
            {
                message = "Vui lòng chọn khách hàng";
                return -1;
            }
            //if (model.Amount == 0)
            //{
            //    message = "Vui lòng nhập số tiền";
            //    return -1;
            //}
            if (model.Type == (int)DepositHistoryConstant.CONTRACT_PAYMENT_TYPE.CHUYEN_KHOAN && model.BankingAccountId == 0)
            {
                message = "Vui lòng chọn tài khoản ngân hàng nhận";
                return -1;
            }
            if (string.IsNullOrEmpty(model.Note))
            {
                message = "Vui lòng nhập nội dung";
                return -1;
            }
            if (!string.IsNullOrEmpty(model.Note) && model.Note.Length > 500)
            {
                message = "Nội dung chỉ được nhập tối đa 500 kí tự";
                return -1;
            }
            if (!string.IsNullOrEmpty(model.Description) && model.Description.Length > 3000)
            {
                message = "Ghi chú chỉ được nhập tối đa 3000 kí tự";
                return -1;
            }

            return result;
        }

        [HttpPost]
        public async Task<IActionResult> AddNewJson(IFormFile imagefile, string jsonData)
        {
            try
            {
                var userLogin = 0;
                if (HttpContext.User.FindFirst(ClaimTypes.NameIdentifier) != null)
                {
                    userLogin = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                }
                ContractPayViewModel model = JsonConvert.DeserializeObject<ContractPayViewModel>(jsonData);
                model.CreatedBy = userLogin;
                if (model.ContractPayDetails == null)
                {
                    model.ContractPayDetails = new List<ContractPayDetailViewModel>();
                }
                var validate = Validate(model, out string messages);
                if (validate < 0)
                {
                    return Ok(new
                    {
                        isSuccess = false,
                        message = messages
                    });
                }
                if (imagefile != null)
                {
                    string _FileName = Guid.NewGuid() + Path.GetExtension(imagefile.FileName);
                    string _UploadFolder = @"uploads/images";
                    string _UploadDirectory = Path.Combine(_WebHostEnvironment.WebRootPath, _UploadFolder);

                    if (!Directory.Exists(_UploadDirectory))
                    {
                        Directory.CreateDirectory(_UploadDirectory);
                    }

                    string filePath = Path.Combine(_UploadDirectory, _FileName);

                    if (!System.IO.File.Exists(filePath))
                    {

Web.CMS/ViewComponents/PagingViewComponent.cs
using Entities.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WEB.CMS.ViewComponents
{
    public class PagingViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Paging pageModel)
        {
            return View(pageModel);
        }
    }
}

Web.CMS/Views/Receipt/AddNew.cshtml
@using Entities.Models
@{
    var allCode_PAY_TYPE = (List<AllCode>)ViewBag.allCode_PAY_TYPE;
    var allCode_CONTRACT_PAY_TYPE = (List<AllCode>)ViewBag.allCode_CONTRACT_PAY_TYPE;
    var listBankingAccount = (List<BankingAccount>)ViewBag.listBankingAccount;
}
<style>
    .white-popup {
        max-width: 1300px !important;
    }

    .content_lightbox .head {
        font-weight: 500 !important;
        font-size: 16px !important;
        margin-bottom: 20px !important;
    }

    .content_lightbox {
        padding: 20px !important;
    }
    .select2-container .select2-dropdown {
        z-index: 1043;
    }
</style>


<div class="grid grid__2 grid-don-hang gap10 mb20">
    <div class="grid-item border">

        <div class="col-md-6 mb10"><label class="lbl mt5 mb0">Loại nghiệp vụ <sup class="red">*</sup></label></div>
        <div class="col-md-12 mb10">
            <select class="form-control" style="width: 100%; height: 34px ;" id="contract-type"
                    onchange="_contract_pay_create_new.OnChooseContractPayType()">
                <option value="-1" disabled selected>Chọn</option>
                @foreach (var item in allCode_CONTRACT_PAY_TYPE)
                {
                    <option value="@item.CodeValue">@item.Description</option>
                }
            </select>
        </div>
        <div class="col-md-12 mb10"><label class="lbl mt5 mb0">Tên đối tượng <sup class="red">*</sup></label></div>
        <div class="col-md-12 m-0 p-0 row">
            <div class="col-md-2">
                <select class="select2" style="width: 60px; height: 34px ;" id="partner_choose_type" onchange="_contract_pay_create_new.OnChoosePartnerType()">
                    <option value="0" disabled>Chọn</option>
                    <option value="1">KH</option>
                    <option value="2">NCC</option>
                    <option value="3">NV</option>
                </select>
            </div>
            <div class="col-md-10 mb10" id="divCustomer">
                <select class="select2 client-select" id="client-select" style="width:100% !important" multiple="multiple"
                        onchange="_contract_pay_create_new.GetDataByClientId()">
                </select>
            </div>
            <div class="col-md-10 mb10" id="divSupplier">
                <select class="select2 supplier-select" id="supplier-select" style="width:100% !important" multiple="multiple"
                        onchange="_contract_pay_create_new.GetDataBySupplierId()">
                </select>
            </div>
            <div class="col-md-10 mb10" id="divEmployee">
                <select class="select2 main-staff-select" id="createdBy" multiple="multiple" style="width:100% !important"
                        onchange="_contract_pay_create_new.GetListBankAccountAdavigo()">
                </select>
            </div>
        </div>

        <div class="col-md-6 mb10">
            <label class="lbl mt5 mb0" id="lblBankAccountRequired">Tài khoản ngân hàng nhận <sup class="red">*</sup></label>
            <label class="lbl mt5 mb0" id="lblBankAccount">Tài khoản ngân hàng nhận</label>
        </div>
        <div class="col-md-12 mb10">
            <select class="form-control" style="width: 100%; height: 34px ;" id="bankingAccount">
                <option value="-1" disabled selected>Chọn</option>
                @foreach (var item in listBankingAccount)
                {
                    <option value="@item.Id">@item.BankId - @item.AccountNumber</option>
                }
            </select>
        </div>

        <div class="col-md-6 mb10"> Ghi chú</div>
        <div class="col-md-12 mb10">
            <textarea class="form-control" id="description" maxlength="3000" style="height: 100px;" autocomplete="off"></textarea>
        </div>
    </div>
    <div class="grid-item border">

        <div class="col-md-6 mb10"> <label class="lbl mt5 mb0"> Hình thức <sup class="red">*</sup></label></div>
        <div class="col-md-12 mb10">
            <select class="form-control" style="width: 100%; height: 34px ;" id="contract-pay-type"
                    onchange="_contract_pay_create_new.OnChoosePaymentType()">
                <option value="0" disabled selected>Chọn</option>
                @foreach (var item in allCode_PAY_TYPE)
                {
                    <option value="@item.CodeValue">@item.Description</option>
                }
            </select>
        </div>

        <div class="col-md-6 mb10"><label class="lbl mt5 mb0"> Số tiền <sup class="red">*</sup></label></div>
        <div class="col-md-12 mb10">
            <input type="text" class="form-control" id="amount" onkeyup="_contract_pay_create_new.FormatNumber();" autocomplete="off">
        </div>

        <div class="col-md-6 mb10"> <label class="lbl mt5 mb0"> Nội dung <sup class="red">*</sup></label></div>
        <div class="col-md-12 mb10">
            <input class="form-control" type="text" id="content" maxlength="500" name="name" placeholder="Nhập text(tối đa 500 kí tự)" autocomplete="off" />
        </div>

        <div class="col-md-6 mb10"> Ảnh đính kèm</div>
        <div class="col-md-12 mb10">
            <input type="file" id="imagefile" name="imagefile" onchange="_contract_pay_create_new.OnChangeImage()">

        </div>

    </div>
</div>
<div class="row m-0 p-0">
    <div class="bg-white border pd10 hidden" id="order-relate" style="display: none; width: 100% !important;">
        <div class="bold gray mb10">Đơn hàng liên quan</div>
        <div class="row">
            <div class="col-md-6">
                <div class="bold mb10">Mã đơn hàng</div>
                <div class="w-100 mb15" style=" padding-right: 10px !important;">
                    <input type="text" class="form-control" name="name" id="orderCodeInput" onkeyup="_contract_pay_create_new.GetOrderDetail()"
                           placeholder="Nhập mã đơn hàng để tìm kiếm nhanh" />
                </div>
            </div>
            <div class="col-md-6 " style="display:none">
                <div class="bold mb10">Ngày tạo</div>
                <div class="wrap_input">
                    <div class="datepicker-wrap" style="width:100%">
                        <input class="form-control date text-left filter_date_daterangepicker" id="filter_date_create_daterangepicker" type="text"
                               name="datetimeCreateFilter" style="        min-width: 200px !important" placeholder="Ngày tạo" />
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive table-default table-gray table-modal scroll-inner">
            <table class="table " id="order-relate-table">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Mã đơn</th>
             
                        <th>Trạng thái</th>
                        <th class="">Nhân viên chính</th>
                        <th class="">Ngày tạo</th>
                        <th class="text-right">Số tiền</th>
                        <th class="text-right">Đã giải trừ</th>
                        <th class="text-right">Chưa giải trừ</th>
                        <th class="text-right">Cần giải trừ</th>
                    </tr>
                </thead>
                <tbody id="body_order_list">
                </tbody>
            </table>
        </div>
        <div class="flex flex-end">
        </div>
    </div>
    <div class="bg-white border pd10 hidden" id="deposit-relate" style="display: none; width: 100% !important;">
        <div class="bold gray mb10">Nạp quỹ liên quan</div>
        <div class="table-responsive table-default table-gray table-modal scroll-inner">
            <table class="table" id="deposit-relate-table">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th style="min-width: 80px;">Mã nạp quỹ</th>
                        <th>Loại quỹ</th>
                        <th>Trạng thái</th>
                        <th style="min-width: 130px;">Người tạo</th>
                        <th class="text-right" style="min-width: 130px;">Số tiền</th>
                    </tr>
                </thead>
                <tbody id="body_deposit_history_list">
                </tbody>
            </table>
        </div>
        <div class="flex flex-end">
        </div>
    </div>
    <div class="bg-white border pd10 hidden" id="supplier-refund-relate" style="display: none; width: 100% !important;">
        <div class="bold gray mb10">Dịch vụ liên quan</div>
        <div class="row">
            <div class="col-md-6">
                <div class="w-100 mb15" style=" padding-right: 10px !important;">
                    <select class="select2 " id="serviceCodeFilter"
                            onchange="_add_payment_voucher.OnCheckedRequest()" multiple="multiple" style="width: 100% !important"> </select>
                </div>
            </div>
        </div>
        <div class="table-responsive table-default table-gray table-modal scroll-inner">
            <table class="table" id="supplier-refund-relate-table">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th style="min-width: 80px;">Mã dịch vụ</th>
                        <th>Ngày bắt đầu - Ngày kết thúc</th>
                        <th>Mã đơn hàng</th>
                        <th style="min-width: 130px;">Nhân viên điều hành</th>
                        <th class="text-right" style="min-width: 130px;">Số tiền</th>
                        <th class="text-right" style="min-width: 130px;">Đã hoàn trả</th>
                        <th class="text-right" style="min-width: 130px;">Có thể hoàn trả</th>
                        <th class="text-right" style="min-width: 130px;">Cần hoàn trả</th>
                    </tr>
                </thead>
                <tbody id="body_supplier_refund_list">
                </tbody>
            </table>
        </div>
        <div class="flex flex-end">
        </div>
    </div>
    <div class="bg-white border pd10 hidden" id="supplier-commision-relate" style="display: none; width: 100% !important;">
        <div class="bold gray mb10">Dịch vụ liên quan</div>
        <div class="row">
            <div class="col-md-6">
                <div class="w-100 mb15" style=" padding-right: 10px !important;">
                    <select class="select2 " id="serviceCodeCommissionFilter"
                            onchange="_add_payment_voucher.OnCheckedRequest()" multiple="multiple" style="width: 100% !important"> </select>
                </div>
            </div>
        </div>
        <div class="table-responsive table-default table-gray table-modal scroll-inner">
            <table class="table" id="supplier-commision-relate-table">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th style="min-width: 80px;">Mã dịch vụ</th>
                        <th>Ngày bắt đầu - Ngày kết thúc</th>
                        <th>Mã đơn hàng</th>
                        <th style="min-width: 130px;">Nhân viên điều hành</th>
                        <th class="text-right" style="min-width: 130px;">Số tiền</th>
                        <th class="text-right" style="min-width: 130px;">Đã trả hoa hồng</th>
                        <th class="text-right" style="min-width: 130px;">Có thể trả hoa hồng</th>
                        <th class="text-right" style="min-width: 130px;">Cần trả hoa hồng</th>
                    </tr>
                </thead>
                <tbody id="body_supplier_commision_list">
                </tbody>
            </table>
        </div>
        <div class="flex flex-end">
        </div>
    </div>
</div>

<div class="text-center" style="margin-top: 20px; margin-bottom: 20px;">
    <button type="submit" class="btn btn-default btn btn-default cancel" onclick="$.magnificPopup.close();">Bỏ qua</button>
    <button type="submit" class="btn btn-default" onclick="_contract_pay_create_new.AddNewContractPay()">Thêm</button>
</div>

<script type="text/javascript" src="~/modules/add_contract_pay_new.js?v=1"></script>
<script>
    _contract_pay_create_new.Initialization();
</script>
@section scripts {
    <script>
        $().ready(function () {
            $('input').attr('autocomplete', 'off');
            setTimeout(function () {
                $('#order-relate').hide()
                $('#deposit-relate').hide()
                $('#supplier-refund-relate').hide()
                $('#supplier-commision-relate').hide()
            }, 1000)
        })
    </script>
}
<style scoped>

    .multiple-select {
        position: relative;
        max-width: 200px !important;
        width: 100%;
    }

    .select2-selection .select2-selection--single {
        height: 34px !important;
    }

    .token-input-client-add {
        min-width: 200px !important;
    }

        .token-input-client-add input {
            background: #fff !important;
            width: 100% !important;
            font-size: 13px !important;
            height: 30px !important;
            line-height: 30px !important;
            border: 1px solid #ccc !important;
            padding: 0 5px !important;
            outline: 0 !important;
            box-shadow: none !important;
            color: #000 !important;
            border-radius: 0.25rem !important;
        }

    .row-main-head .down-up .form-down {
        width: 345px !important;
    }

    .form-control {
        background: #fff;
        width: 100%;
        font-size: 13px;
        height: 30px;
        line-height: 30px;
        border: 1px solid #ccc;
        padding: 0 5px;
        outline: 0;
        box-shadow: none;
        color: #000;
        border-radius: 0.25rem !important;
    }

    .background-disabled {
        background: #eee !important;
    }
</style>

Web.CMS/Views/Receipt/Search.cshtml
@{
    Layout = null;
}
@using Entities.ViewModels
@using Utilities
@model GenericViewModel<ContractPayViewModel>

@if (Model == null || Model.ListData == null || Model.ListData.Count == 0)
{
    <div class="search-null center mb40">
        <div class="mb24">
            <img src="/images/graphics/icon-search.png" alt="">
        </div>
        <h2 class="title txt_24">Không tìm thấy kết quả</h2>
        <div class="gray">Chúng tôi không tìm thấy thông tin mà bạn cần, vui lòng thử lại</div>
    </div>
}
else
{
    <div class="table-responsive table-default table-gray">
        <table class="table table-nowrap">
            <thead>
                <tr>
                    <th style="width: 30px;">STT</th>
                    <th style="width: 100px;">Mã phiếu</th>
                    <th style="width: 140px;">Loại nghiệp vụ</th>
                    <th style="width: 100px;">Hình thức</th>
                    <th style="width: 100px;">Khách hàng</th>
                
                    <th style="width: 100px;" class="text-right">Số tiền</th>
                    <th style="width: 200px;">Nội dung</th>
                    <th style="width: 120px;">Đơn hàng</th>
                    <th style="width: 140px;">Ngày tạo</th>
                    <th style="width: 140px;">Người tạo</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListData != null && Model.ListData.Count > 0)
                {
                    var counter = (Model.CurrentPage - 1) * Model.PageSize;
                    foreach (var item in Model.ListData)
                    {
                        counter++;
                        <tr>
                            <td class="center ">@counter</td>
                            <td class="text-nowrap">
                                <a class="blue" href="/Receipt/Detail?contractPayId=@item.PayId">
                                    @item.BillNo
                                </a>
                            </td>
                            <td class="text-break">@item.ContractPayType</td>
                            <td class="text-break">@item.PayTypeStr</td>
                            <td class="text-break">
                                <a href="/CustomerManager/Detail?id=@item.ClientId"><span class="blue"> @item.ClientName</span></a>
                            </td>
                    
                            <td class="text-right">
                                @if (item.Type == (int)DepositHistoryConstant.CONTRACT_PAY_TYPE.THU_TIEN_DON_HANG)
                                {
                                    @if (item.TotalDeposit >= item.Amount)
                                    {
                                        <div class="green">@item.TotalDeposit.ToString("N0")/ </div>
                                    }
                                    else
                                    {
                                        <div class="red">@item.TotalDeposit.ToString("N0")/ </div>
                                    }
                                    <div>@item.Amount.ToString("N0")</div>
                                }
                               
                            </td>
                            <td class=" text-break">@item.Note</td>
                            <td class=" text-break">
                                @if (item.Type == (int)DepositHistoryConstant.CONTRACT_PAY_TYPE.THU_TIEN_DON_HANG && item.DataContent != null)
                                {
                                    var counterContent = 1;
                                    foreach (var dataNo in item.DataContent)
                                    {
                                        <a class="blue" href="/Order/@dataNo.DataId">
                                            @dataNo.DataNo
                                        </a>
                                        @if (counterContent < item.DataContent.Count)
                                        {
                                            <span>,</span>
                                        }
                                        counterContent += 1;
                                    }
                                }
                               
                            </td>
                            @if (item.CreatedDate != null)
                            {
                                <td class=" text-break">@item.CreatedDate.Value.ToString("dd-MM-yyyy HH:mm")</td>
                            }
                            else
                            {
                                <td class=" text-break">@item.CreatedDate</td>
                            }
                            <td class=" text-break">@item.UserName </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
}

@await Component.InvokeAsync("Paging", new
{
    pageModel = new Paging()
    {
        TotalRecord = Model.TotalRecord,
        TotalPage = Model.TotalPage,
        CurrentPage = Model.CurrentPage,
        PageSize = Model.PageSize,
        RecordName = "kết quả lọc",
        PageAction = "_receipt_service.OnPaging({0})"
    }
})